project:
  type: website
  output-dir: docs

website:
  title: "Pedro"
  description: "Site Acadêmico"
  site-url: "https://pedroallmeiida.github.io/meu_site"
  
  navbar:
    background: primary
    search: true
    left:
      - text: "Início"
        file: index.qmd
      - text: "Publicações"
        file: publications.qmd
      - text: "Projetos"
        file: projects.qmd
      - text: "Disciplinas"
        file: courses.qmd
      - href: slides/
        text: Slides
      - text: "CV"
        file: cv.qmd
      - text: "Contato"
        file: contact.qmd
    right:
      - icon: github
        href: https://github.com/pedroallmeiida
      - icon: Linkedin
        href: https://www.linkedin.com/in/pedro-almeida-1b9676122/

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Pesquisa"
        contents:
          - publications.qmd
          - projects.qmd
      - section: "Ensino"
        contents:
          - courses.qmd
          - materials.qmd

format:
  html:
    theme: 
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true




